{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jitsi.serviceAccountName" . }}
  labels:
{{ include "jitsi.labels" . | indent 4 }}
{{- end -}}
